name: macro_notify
description: "Um aplicativo Flutter que monitora notificações usando NotificationListenerService com interface moderna e logs detalhados."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Banco de dados
  sqflite: ^2.3.3
  path: ^1.9.0

  # Utilidades
  intl: ^0.19.0
  uuid: ^4.4.0

  # Notificações
  flutter_local_notifications: ^17.2.3

  # Background (VERSÃO NOVA COMPATÍVEL)
  workmanager: ^0.9.0+3

  # Permissões
  permission_handler: ^12.0.1

  # Estado
  provider: ^6.1.2

  # Persistência
  shared_preferences: ^2.2.3

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

  # Conectividade
  connectivity_plus: ^6.0.3

  # Apps instalados
  installed_apps: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
